/**
 * OS ÍCONES DE LINHA (06/10/2026): o catálogo que as peças vetoriais desenham (ícone com frase, cartões em
 * linha). Espelho dos nomes de worker/remotion/src/sob-medida/icones.ts e icones-de-linha.ts (o desenho mora
 * lá; o worker não lê o app). O redator SUGERE o nome; o JEV ESCOLHE entre os candidatos
 * (lib/media/editor-por-comando/icone-pelo-jev.ts). Gerado por worker/remotion/icones-de-linha.mjs.
 */
export const ICONES_DE_LINHA: Record<string, string> = {
 "dinheiro": "dinheiro",
 "cifrao": "cifrao",
 "carteira": "carteira",
 "cofre": "cofre",
 "relogio": "relogio",
 "ampulheta": "ampulheta",
 "pessoas": "pessoas",
 "pessoa": "pessoa",
 "foguete": "foguete",
 "alvo": "alvo",
 "sobe": "sobe",
 "cai": "cai",
 "grafico": "grafico",
 "cruz": "cruz",
 "livro": "livro",
 "biblia": "biblia",
 "coracao": "coracao",
 "raio": "raio",
 "cadeado": "cadeado",
 "casa": "casa",
 "mundo": "mundo",
 "check": "check",
 "x": "x",
 "lampada": "lampada",
 "megafone": "megafone",
 "calendario": "calendario",
 "escudo": "escudo",
 "coroa": "coroa",
 "chave": "chave",
 "aperto": "aperto",
 "estrela": "estrela",
 "igreja": "igreja",
 "mensagem": "mensagem",
 "telefone": "telefone",
 "carrinho": "carrinho",
 "ferramenta": "ferramenta",
 "mapa": "mapa",
 "bussola": "bussola",
 "montanha": "montanha",
 "semente": "semente",
 "fogo": "fogo",
 "trofeu": "trofeu",
 "maleta": "maleta",
 "loja": "loja",
 "predio": "predio",
 "computador": "computador",
 "video": "video",
 "camera": "camera",
 "microfone": "microfone",
 "olho": "olho",
 "cerebro": "cerebro",
 "balanca": "balanca",
 "presente": "presente",
 "pao": "pao",
 "peixe": "peixe",
 "barco": "barco",
 "ovelha": "ovelha",
 "oracao": "oracao",
 "luz": "luz",
 "agua": "agua",
 "caminho": "caminho",
 "escada": "escada",
 "alerta": "alerta",
 "pergunta": "pergunta",
 "ideia": "ideia",
 "seta": "seta",
 "repetir": "repetir",
 "tempo": "tempo",
 "documento": "documento",
 "contrato": "contrato",
 "email": "email",
 "compartilhar": "compartilhar",
 "despertador": "despertador, acordar cedo, rotina da manhã, hora certa",
 "tv-desligada": "tela desligada, desligar a TV, menos tela, desconectar",
 "celular": "celular, aplicativo, rede social no celular",
 "sem-notificacao": "silenciar notificações, foco, sem distração",
 "notificacao": "notificação, aviso, alerta chegando",
 "proibido": "proibido, não faça, pare, evitar",
 "tesoura": "cortar, edição de vídeo, corte, aparar",
 "claquete": "gravação, take, cena, produção de vídeo",
 "filme": "vídeo, filme, rolo, edição",
 "play": "play, assistir, vídeo, começar",
 "edicao": "editar, escrever, ajustar, revisar",
 "camadas": "camadas, linha do tempo, sobreposição, plataforma",
 "robo": "robô, automação, inteligência artificial, agente",
 "brilho": "IA, mágica, novo, automático, brilho",
 "varinha": "mágica, fazer sozinho, transformar, automático",
 "automacao": "fluxo automatizado, processo, integração, automação",
 "engrenagem": "configurar, sistema, processo, ajuste",
 "codigo": "código, programação, desenvolvedor",
 "terminal": "terminal, comando, software, programação",
 "nuvem": "nuvem, online, armazenamento, servidor",
 "banco": "dados, banco de dados, informação guardada",
 "chip": "processador, tecnologia, máquina, computação",
 "teclado": "digitar, escrever, trabalho no computador",
 "cafe": "café, pausa, manhã, conversa",
 "cama": "dormir, descanso, sono",
 "lua": "noite, dormir, descanso",
 "sol": "dia, manhã, energia, clareza",
 "haltere": "treino, academia, disciplina física, força",
 "livro-aberto": "ler, estudar, aprender, leitura",
 "caneta": "escrever, anotar, assinar",
 "lista-check": "lista de tarefas, checklist, organizar",
 "cronometro": "cronômetro, prazo, tempo contado, rapidez",
 "velocimetro": "velocidade, desempenho, medir, produtividade",
 "joinha": "aprovado, gostei, positivo, curtir",
 "nao-gostei": "reprovado, não gostei, negativo",
 "certo": "certo, correto, feito, aprovado",
 "errado": "errado, incorreto, não faça",
 "equipe": "equipe, clientes, público, comunidade",
 "pessoa-check": "cliente conquistado, pessoa aprovada, contratação",
 "mao": "pare, mão, atenção, oi",
 "foco": "foco, concentração, mirar",
 "porcentagem": "porcentagem, desconto, taxa",
 "etiqueta": "preço, etiqueta, oferta, valor",
 "recibo": "conta, nota, gasto, pagamento",
 "cartao": "cartão, pagamento, compra",
 "pizza": "divisão, fatia, participação",
 "crescimento": "crescimento, resultado subindo, evolução",
 "medalha": "prêmio, reconhecimento, melhor, qualidade",
 "pasta": "arquivos, organização, documentos",
 "link": "link, conexão, ligar",
 "busca": "procurar, pesquisar, buscar",
 "conversa": "conversa, chat, mensagens, atendimento",
 "podcast": "podcast, áudio, entrevista",
 "fone": "ouvir, áudio, música, atenção",
 "imagem": "imagem, foto, arte",
 "paleta": "design, cores, criatividade, marca",
 "mira": "mirar, precisão, alvo exato",
 "info": "informação, saiba, dica",
 "escudo-check": "segurança, proteção, garantia",
 "calendario-check": "agenda cumprida, compromisso, constância",
 "calendario-x": "falta, compromisso cancelado, sem agenda",
 "cerebro-ia": "inteligência, IA pensando, mente, estratégia",
 "mao-dinheiro": "receber, pagamento, ganhar dinheiro",
 "caminhao": "entrega, frete, logística",
 "pacote": "produto, pacote, entrega",
 "ondas-de-som": "voz, áudio, som, fala",
 "mudo": "silêncio, sem som, mudo",
 "olho-fechado": "esconder, não ver, ignorar",
 "sair": "sair, ir embora, deixar",
 "ampliar": "aproximar, detalhe, olhar de perto",
 "desfazer": "desfazer, voltar atrás, corrigir",
 "atualizar": "atualizar, recomeçar, repetir o ciclo",
 "bandeira": "meta, chegada, objetivo, marco",
 "broto": "crescimento, começo, cultivar",
 "instituicao": "instituição, banco, governo, autoridade",
 "diamante": "valor, premium, luxo, raro"
};

export const NOMES_DOS_ICONES_DE_LINHA = Object.keys(ICONES_DE_LINHA);
